import { type UserProfile } from '../types'

export interface DemoProfile {
  name: string
  label: string
  profile: UserProfile
}

const base: UserProfile = {
  studentType: null, visaType: null, school: '', major: '', year: null,
  careerField: null, hasSSN: null, hasITIN: null, homeCountry: null,
  hasUSBankAccount: null, monthlyIncome: null, receivesParentalSupport: null,
  topSpendingCategories: [], isFirstCard: null, hasExistingCard: null,
  creditHistory: null, creditScore: null, existingCardType: null,
  currentUtilization: null, missedPayment: null, returningGoal: null,
  isEmployed: null, workStudyAccess: null, onCampusWorkAuth: null,
  offCampusWorkAuth: null, isAuthorizedUser: null, hasHomeCreditHistory: null,
  hasTrustedUSContact: null, hasBeenRejected: null, goal: null, approvedCard: null,
}

export const DEMO_PROFILES: DemoProfile[] = [
  {
    name: 'Maya',
    label: 'A — Domestic · first card · $0 income · no credit · Tech',
    profile: {
      ...base,
      studentType: 'domestic',
      isFirstCard: true,
      hasExistingCard: false,
      monthlyIncome: '$0',
      creditHistory: 'none',
      creditScore: 'none',
      workStudyAccess: true,
      receivesParentalSupport: true,
      goal: 'build-credit',
      careerField: 'tech',
      year: '1st',
      hasUSBankAccount: true,
      hasSSN: true,
      topSpendingCategories: ['Groceries', 'Subscriptions'],
      isEmployed: false,
      hasBeenRejected: false,
    },
  },
  {
    name: 'Priya',
    label: 'B — F-1 · no SSN · no ITIN · $0 income · Healthcare',
    profile: {
      ...base,
      studentType: 'international',
      visaType: 'F1',
      hasSSN: false,
      hasITIN: false,
      monthlyIncome: '$0',
      onCampusWorkAuth: true,
      offCampusWorkAuth: false,
      hasTrustedUSContact: true,
      homeCountry: 'India',
      hasHomeCreditHistory: false,
      goal: 'build-credit',
      careerField: 'healthcare',
      isFirstCard: true,
      hasExistingCard: false,
      creditHistory: 'none',
      creditScore: 'none',
      hasUSBankAccount: true,
      receivesParentalSupport: true,
      topSpendingCategories: ['Dining', 'Groceries'],
      hasBeenRejected: false,
      year: '1st',
    },
  },
  {
    name: 'Sofia',
    label: 'C — F-1 · ITIN · $500–1k · rewards · dining · Finance',
    profile: {
      ...base,
      studentType: 'international',
      visaType: 'F1',
      hasSSN: false,
      hasITIN: true,
      monthlyIncome: '$500-1000',
      offCampusWorkAuth: false,
      onCampusWorkAuth: true,
      homeCountry: 'Brazil',
      hasHomeCreditHistory: true,
      goal: 'rewards',
      topSpendingCategories: ['Dining', 'Online shopping'],
      careerField: 'finance',
      isFirstCard: true,
      hasExistingCard: false,
      creditHistory: 'none',
      creditScore: 'none',
      hasUSBankAccount: true,
      receivesParentalSupport: 'sometimes',
      hasBeenRejected: false,
      year: '2nd',
    },
  },
  {
    name: 'Jordan',
    label: 'D — Domestic · returning · fair score · over 30% util · Finance',
    profile: {
      ...base,
      studentType: 'domestic',
      isFirstCard: false,
      hasExistingCard: true,
      existingCardType: 'student',
      creditScore: 'fair',
      creditHistory: 'some',
      currentUtilization: 'over30',
      missedPayment: false,
      returningGoal: 'add-second',
      goal: 'rewards',
      topSpendingCategories: ['Dining', 'Groceries'],
      careerField: 'finance',
      hasSSN: true,
      hasUSBankAccount: true,
      monthlyIncome: '$500-1000',
      receivesParentalSupport: false,
      isEmployed: true,
      workStudyAccess: false,
      hasBeenRejected: false,
      year: '3rd',
    },
  },
  {
    name: 'Yuna',
    label: 'E — OPT · new SSN · no US credit · build-credit · Engineering',
    profile: {
      ...base,
      studentType: 'international',
      visaType: 'OPT',
      hasSSN: true,
      hasITIN: false,
      monthlyIncome: '$500-1000',
      isFirstCard: true,
      hasExistingCard: false,
      creditHistory: 'none',
      creditScore: 'none',
      goal: 'build-credit',
      careerField: 'engineering',
      hasUSBankAccount: true,
      offCampusWorkAuth: true,
      onCampusWorkAuth: false,
      homeCountry: 'South Korea',
      receivesParentalSupport: false,
      topSpendingCategories: ['Groceries', 'Transport'],
      hasBeenRejected: false,
      year: '2nd',
    },
  },
]
